development:
  adapter: mysql2
  encoding: utf8
  database: mquc
  username: root

production:
  adapter: postgresql
  encoding: utf8
  database: d87sodnbq16b9a
  username: btzfurbhqtzzwi
  password: "5432"
